---
name: "Documentation"

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow running this workflow manually (Actions tab)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: "Build Documentation"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install UV"
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true

      - name: "Build pages artifact"
        run: |
          cd docs/
          uv run zensical build --clean

      - name: "Upload pages artifact"
        uses: actions/upload-pages-artifact@v5
        if: github.event_name != 'pull_request'
        with:
          path: docs/public

  deploy:
    name: "Deploy Documentation"
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: "Configure GitHub Pages"
        uses: actions/configure-pages@v6
          
      - name: "Deploy pages artifact"
        id: deployment
        uses: actions/deploy-pages@v5
