---
# NOTE: This workflow requires that GitHub Actions is allowed
#   to create and approve pull requests.
#   See: https://stackoverflow.com/a/73155199/146622
# NOTE: This workflow needs a GitHub App with the following repository permissions:
# - Contents: Read and write
# - Pull requests: Read and write
# - Metadata: Read-only (required)
# - Workflows: Read and write
# And the following Actions repository secrets:
# - APP_ID: The ID of the GitHub APP
# - APP_PRIVATE_KEY: The contents of the GitHub App's private key .pem file
name: "Update GitHub Actions"

on:  # yamllint disable-line rule:truthy
  schedule:
    # Run at 6:00 on Saturday
    - cron: "0 6 * * 6"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-actions:
    name: "Update GitHub Actions"
    runs-on: ubuntu-latest
    steps:
      - name: "Generate GitHub App token"
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Renovate"
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          # Tell Renovate which repository to process (the current one).
          RENOVATE_REPOSITORIES: ${{ github.repository }}
